### ISSUE TITLE
Cant update bluecord

### ISSUE THREAD

**Issue by Smilycirus** [bluemods/Bluecord#22]
I've been on bluecord 2.2 the entire time I have had bluecord and didn't know there was update until a friend told me, so in the app I tried to update from bluecord menu but it says I'm on latest version, and going to website also says latest version is 2.2. idk what to do.

**Comment by Smilycirus** [comment]
I can send screenshots of the app and website if needed too

**Comment by xemulat** [comment]
it's abandoned

**Comment by Smilycirus** [comment]
> it's abandoned

Wdym it's abandoned?

**Comment by bluemods** [comment]
Closing due to new release

See here: https://github.com/bluemods/Bluecord/releases/tag/v2.3
