### ISSUE TITLE
Role count at servers is always 0

### ISSUE THREAD

**Issue by ArtemCucumber** [bluemods/Bluecord#26]
Like this one at terraria's discord server
![Screenshot_20240421-114955_Bluecord](https://github.com/bluemods/Bluecord/assets/93423706/727192e1-dcd5-4c59-a830-d14e6a4eecc5)
Version 2.2, android 11

**Comment by bluemods** [comment]
https://github.com/bluemods/Bluecord/commit/f6834f81d1f51d9ba3df33129993b3b298c4e5a0
