### ISSUE TITLE
Bluecord voicecall

### ISSUE THREAD

**Issue by ujebehege** [bluemods/Bluecord#29]
Bluecord 2.2 constantly disables when trying to enter a conversation(voice channel ) is there a way to fix it? I don't really want to use the new version. A week ago it was okay but now its doesnt work

**Comment by bluemods** [comment]
The app will be updated soon to fix this issue.

**Comment by K4sum1** [comment]
Holy shit Bluecord back?!?!?

**Comment by bluemods** [comment]
Closing due to new release that resolves this issue.

See here: https://github.com/bluemods/Bluecord/releases/tag/v2.3
