### ISSUE TITLE
Option to hide voice/video call options

### ISSUE THREAD

**Issue by K4sum1** [bluemods/Bluecord#32]
I don't ever use them, so I would prefer to have them gone so I don't accidentally tap them.

**Comment by yutaplug** [comment]
> I don't ever use them, so I would prefer to have them gone so I don't accidentally tap them.

you mean the buttons? there is already a option for that in the theme mods.

**Comment by K4sum1** [comment]
I appear to have the option already checked, I guess it's broken then.

**Comment by yutaplug** [comment]
> I appear to have the option already checked, I guess it's broken then.
> 
> 

it works for me, idk.

**Comment by K4sum1** [comment]
I think I remember it working in 1.5.4, but not on 2.x
![Screenshot_20240823-175947669 (1)](https://github.com/user-attachments/assets/26ddceb1-79a3-411d-9200-52f87cf84a6f)
![Screenshot_20240823-175924137 (1)](https://github.com/user-attachments/assets/1ee40b4e-3610-4d10-b1f5-62ef826a98d4)

**Comment by yutaplug** [comment]
> I think I remember it working in 1.5.4, but not on 2.x
> ![Screenshot_20240823-175947669 (1)](https://github.com/user-attachments/assets/26ddceb1-79a3-411d-9200-52f87cf84a6f)
> ![Screenshot_20240823-175924137 (1)](https://github.com/user-attachments/assets/1ee40b4e-3610-4d10-b1f5-62ef826a98d4)
> 

oh, it doesnt work for that buttons in that menu, but it does work on the other ones like in the user profile or the friend list. i mean, its already useful.

**Comment by bluemods** [comment]
https://github.com/bluemods/Bluecord/commit/b23295aef692b1ccaf665efe4d63fc4f75a3af10
