### ISSUE TITLE
you need to update your app to do this action

### ISSUE THREAD

**Issue by SocksSockington** [bluemods/Bluecord#37]
i tried changing my pfp, but it gave me an error to update the app
![Screenshot_20240828-050724](https://github.com/user-attachments/assets/b47204ba-fa6c-41aa-aee5-0240111873d3)

sorry if i sound weird or did this wrong, im new to github so idk how this whole process works

**Comment by SocksSockington** [comment]
ok wait it randomly fixed itself after awhile,

**Comment by bluemods** [comment]
Likely was a challenge for being on a high risk IP / something similar
