### ISSUE TITLE
you cannot build this "safely"

### ISSUE THREAD

**Issue by kekkodance** [bluemods/Bluecord#6]
the build instructions make no sense, you made the app "open-source" but didn't include the "smali patcher", what if the sussy stuff is in it? you're making your users do something you used to disallow and ban people for (decompilation) just to get a patcher you don't want to release. by "safely" i mean you cannot fully audit this app.

**Comment by bluemods** [comment]
> but didn't include the "smali patcher"

There isn't one in extistence, it is manually done. Feel free to submit one if you would like to see it faster.
