### ISSUE TITLE
APK PHONE

### ISSUE THREAD

**Issue by Guaperoide3000** [bluemods/Bluecord#7]
Method for made the APK in phones pls

**Comment by bluemods** [comment]
I don't understand what you are trying to ask.

**Comment by Guaperoide3000** [comment]
How can I made the APK to phones without using a pc?

**Comment by Mechite** [comment]
This does not belong in a GitHub issue (or frankly anywhere).
If you would like to achieve this (or what I'm assuming you are asking), perhaps use a shell like Termux or something to build.
Blue won't support you if you can't have a basic development environment (or really, won't support you at all; this repo makes sense for contributions, issues/bugs, peace of mind for security, and nothing more).

In any case, you can use the prebuilt binaries.
Perhaps it makes sense for Blue to set up CI/CD so people can just grab artifacts that they can trust.

Pointing to the latest artifact emitted by GitHub Actions would be a good way to get peace of mind, so there is no reason to build on your own unless there is something to contribute.
